from app.schemas.cnic import *
from app.schemas.timestamp import *
from app.schemas.user import *
from app.schemas.role import *
from app.schemas.cam_type import *;
from app.schemas.location import *;
from app.schemas.camera import *;
from app.schemas.number_plate_timestamp import *;
from app.schemas.guest import *;