import os

file_path = r"C:\Users\Administrator\.gemini\antigravity\scratch\elsaenergy-agritech\Elsaenergy-Agritech-main\src\App.jsx"

if not os.path.exists(file_path):
    print("Error: App.jsx not found.")
    exit(1)

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = [
    # Devices Tab Header
    (
        '          {tab==="devices" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3">Manage Devices</span>',
        '          {tab==="devices" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3 d-flex align-items-center"><span>Manage Devices</span><TourHelper tourMode={tourMode} title="Device Fleet Management" concept="A central directory of all EV charging stations, building meters, and network gateways connected to the system." value="Enables remote monitoring, instant troubleshooting, and automated software updates across all your physical assets." tip="Click \'Add Device\' to simulate adding a new charging bay or smart meter to your network." /></span>'
    ),
    # Devices Tab Toolbar
    (
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Devices - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar d-flex gap-3">',
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Devices - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar d-flex gap-3 align-items-center">{tourMode && <TourHelper tourMode={tourMode} title="Bulk Operations" concept="Administrative controls to provision new hardware, delete deprecated devices, or export data reports." value="Accelerates deployment of new charger installations and exports device records for compliance audits." tip="Point out the batch delete safety option, preventing manual one-by-one deletions." />}'
    ),
    # Devices Tab Organizations Left Panel
    (
        '<div style={{ color: "#252F4A", fontSize: "14px", fontWeight: "600", marginBottom: "16px", paddingLeft: "8px" }}>Organizations</div>',
        '<div style={{ color: "#252F4A", fontSize: "14px", fontWeight: "600", marginBottom: "16px", paddingLeft: "8px", display: "flex", alignItems: "center" }}><span>Organizations</span><TourHelper tourMode={tourMode} title="Organizational Segments" concept="Groups devices and users by business division, location, or customer account." value="Maintains data privacy and access control, ensuring operators only see and configure assets they own." tip="Select different organizations like \'All\', \'Bakery\' or \'NUST\' to filter the device list instantly." /></div>'
    ),
    # Devices Tab Filters Row
    (
        '                  {/* Filters Row */}\n                  <div style={{ paddingBottom: "16px", borderBottom: "1px solid #F1F1F4", display: "flex", gap: "12px", flexWrap: "wrap", alignItems: "center" }}>',
        '                  {/* Filters Row */}\n                  <div style={{ paddingBottom: "16px", borderBottom: "1px solid #F1F1F4", display: "flex", gap: "12px", flexWrap: "wrap", alignItems: "center" }}>\n                    {tourMode && <TourHelper tourMode={tourMode} title="Asset Filtering" concept="Quick filters to find devices based on status (Online/Offline), template type, or owner." value="Minimizes time spent searching through large fleets, making it easy to isolate and diagnose offline equipment." tip="Change the status dropdown to \'Offline\' and click \'Query\' to see devices needing immediate attention." />}'
    ),
    # Devices Tab Operation Header
    (
        '                          <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Switch</th>\n                          <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}>Operation</th>',
        '                          <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Switch</th>\n                          <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}><span style={{ display: "inline-flex", alignItems: "center" }}><span>Operation</span><TourHelper tourMode={tourMode} title="Individual Device Controls" concept="Quick-action shortcuts to inspect live telemetry (eye), edit parameters (pen), or decommission (trash) a specific device." value="Reduces administrative overhead by putting common control tasks just one click away." tip="Click the yellow eye icon next to a device to view its detailed diagnostics log." /></span></th>'
    ),

    # Organizations Tab Header
    (
        '          {tab==="organizations" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3">Manage Organizations</span>',
        '          {tab==="organizations" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3 d-flex align-items-center"><span>Manage Organizations</span><TourHelper tourMode={tourMode} title="Tenancy & Account Hierarchy" concept="Manages company accounts, branches, or customer divisions within the multi-tenant system." value="Allows utility providers and building operators to run a single software instance while isolating client datasets safely." tip="Point out how different business locations can be designated as individual organizations." /></span>'
    ),
    # Organizations Tab Toolbar
    (
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Organizations - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar">',
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Organizations - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar d-flex align-items-center gap-2">{tourMode && <TourHelper tourMode={tourMode} title="Creating Customer Portals" concept="Provisioning a new client or subsidiary with its own isolated workspace and assets." value="Enables instant scaling as new businesses join your smart energy ecosystem." tip="Use this button during client setup to configure custom tenant names and permissions." />}'
    ),
    # Organizations Tab Operation Header
    (
        '                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Status</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}>Operation</th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      {filteredOrgs.map(o => (',
        '                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Status</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}><span style={{ display: "inline-flex", alignItems: "center" }}><span>Operation</span><TourHelper tourMode={tourMode} title="Tenant Life-cycle Actions" concept="Modify tenant profile settings or revoke access entirely when subscription status changes." value="Gives operators absolute control over access credentials and subscription states." tip="Explain that deleting an organization cleanly unlinks all member devices." /></span></th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      {filteredOrgs.map(o => ('
    ),

    # Users Tab Header
    (
        '          {tab==="users" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3">Manage Users</span>',
        '          {tab==="users" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3 d-flex align-items-center"><span>Manage Users</span><TourHelper tourMode={tourMode} title="Identity & Access Control" concept="Directory of all administrative staff, building managers, drivers, and external auditors." value="Secures your grid controls by verifying who is authorized to modify setpoints and limits." tip="Show how roles distinguish access between deep settings overrides and view-only diagnostics." /></span>'
    ),
    # Users Tab Toolbar
    (
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Users - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar d-flex gap-3">',
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Users - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar d-flex gap-3 align-items-center">{tourMode && <TourHelper tourMode={tourMode} title="Access Provisioning" concept="Invite team members and define their roles, or export user lists for compliance reviews." value="Simplifies onboarding for new personnel and supports security access reviews." tip="Explain that exporting user lists helps during security audits to verify access privileges." />}'
    ),
    # Users Tab Table Header
    (
        '                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Role</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Status</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}>Operation</th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      {[',
        '                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}><span style={{ display: "inline-flex", alignItems: "center" }}><span>Role</span><TourHelper tourMode={tourMode} title="Role-Based Access (RBAC)" concept="Determines what permissions (Admin, User, Viewer) a user has on the dashboard." value="Prevents accidental or unauthorized modifications to sensitive grid limits." tip="Show the color-coded roles: blue for Admin, yellow for User, and purple for Viewer." /></span></th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Status</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}><span style={{ display: "inline-flex", alignItems: "center" }}><span>Operation</span><TourHelper tourMode={tourMode} title="User Management Actions" concept="Update profiles, reset passwords, or suspend users who leave the company." value="Ensures immediate revocation of access for security and administrative changes." tip="Point out how you can edit user roles directly in the list." /></span></th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      {['
    ),

    # Gateways Tab Header
    (
        '          {tab==="gateways" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3">Manage Gateway</span>',
        '          {tab==="gateways" && (\n            <div className="card card-flush h-lg-100" style={{ backgroundColor: \'#ffffff\', borderRadius: \'12px\', minHeight: \'calc(100vh - 150px)\', boxShadow: \'0px 0px 20px 0px rgba(76, 87, 125, 0.02)\', border: \'1px solid #F1F1F4\' }}>\n              {/* Card Header */}\n              <div className="card-header pt-7 px-8 pb-5 d-flex justify-content-between align-items-center" style={{ borderBottom: \'1px solid #F1F1F4\' }}>\n                <div>\n                  <h3 className="card-title align-items-start flex-column">\n                    <span className="card-label fw-bold text-gray-900 fs-3 d-flex align-items-center"><span>Manage Gateway</span><TourHelper tourMode={tourMode} title="Grid Communication Hubs" concept="Hardware bridges that connect local sensors, chargers, and building meters to the cloud software." value="Ensures continuous data feeds from physical devices, even during local internet disruptions." tip="Check the online status of your gateways to verify active telemetry streams." /></span>'
    ),
    # Gateways Tab Toolbar
    (
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Gateway - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar d-flex gap-3">',
        '                    <span className="text-gray-500 mt-1 fw-semibold fs-7 d-block">Manage Gateway - List</span>\n                  </h3>\n                </div>\n                <div className="card-toolbar d-flex gap-3 align-items-center">{tourMode && <TourHelper tourMode={tourMode} title="Hub Expansion Controls" concept="Registers new gateway hubs or exports serial number tables for tracking." value="Simplifies installation setups when adding new building wings or depot chargers." tip="Use this button to register a newly installed gateway serial number in seconds." />}'
    ),
    # Gateways Tab Table Header
    (
        '                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Serial Number</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>IP Address</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}>Operation</th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      {[',
        '                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}>Serial Number</th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600" }}><span style={{ display: "inline-flex", alignItems: "center" }}><span>IP Address</span><TourHelper tourMode={tourMode} title="Local Network Address" concept="The local network address used to communicate directly with local hardware units." value="Enables remote network testing and local configuration directly on-site." tip="Confirm the IP address matches your local substation router configuration." /></span></th>\n                        <th style={{ padding: "14px 16px", color: "#252F4A", fontSize: "13px", fontWeight: "600", textAlign: "right" }}><span style={{ display: "inline-flex", alignItems: "center" }}><span>Operation</span><TourHelper tourMode={tourMode} title="Hub Control Actions" concept="View gateway settings, reboot the bridge, or delete decommissioned hub records." value="Allows quick network resets from anywhere without visiting the hardware." tip="Click the view eye icon to perform remote network connectivity tests." /></span></th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      {['
    ),

    # Live Session - Driver Side SLs
    (
        '<SL>Smart Charging Controls</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Smart Charging Controls", concept: "Automated toggles to optimize cost, battery health, and solar utilization.", value: "Saves energy and extends battery life automatically by adjusting charging speeds based on real-time grid conditions.", tip: "Toggle \'Solar Sync\' to charge using 100% clean, free energy from the building\'s roof panel." }}>Smart Charging Controls</SL>'
    ),
    (
        '<SL>Vehicle Health</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Vehicle Health Indicators", concept: "Real-time battery diagnostics including temperature, health state, voltage, and charging efficiency.", value: "Helps predict battery degradation and avoid unexpected thermal breakdowns during fast charging.", tip: "Point out the Battery SoH (State of Health) at 97% to show that the battery remains highly efficient." }}>Vehicle Health</SL>'
    ),

    # Live Session - Operator View
    (
        '                <div style={{background:C.amberLight,border:`1px solid ${C.amber}40`,borderRadius:14,padding:"12px 18px",display:"flex",gap:12,alignItems:"flex-start"}}>\n                  <span style={{fontSize:24}}>🤖</span>',
        '                <div style={{background:C.amberLight,border:`1px solid ${C.amber}40`,borderRadius:14,padding:"12px 18px",display:"flex",gap:12,alignItems:"flex-start"}}>\n                  <span style={{fontSize:24, display:"flex", alignItems:"center"}}>🤖{tourMode && <TourHelper tourMode={tourMode} title="AI Tariff Optimizer Advice" concept="Intelligent predictions warning when utility prices are about to spike." value="Proactively shifts heavy electrical loads out of expensive hours, preventing massive utility bills." tip="Explain to the client how the system auto-schedules high-power tasks for cheap periods." />}</span>'
    ),
    (
        '                      <Card key={i} accent={statusColor} style={{padding:"18px"}}>\n                        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:12}}>\n                          <div style={{fontSize:14,fontWeight:700}}>{bay.id}</div>',
        '                      <Card key={i} accent={statusColor} style={{padding:"18px"}}>\n                        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:12}}>\n                          <div style={{fontSize:14,fontWeight:700,display:"flex",alignItems:"center"}}><span>{bay.id}</span><TourHelper tourMode={tourMode} title="Active Bay Telemetry" concept="Status and state-of-charge for individual charging bays in your depot." value="Provides operators real-time feedback on bay utilization, energy sources, and electrical load." tip="Point out the green \'via solar\' tag indicating a vehicle charging on 100% free rooftop energy." /></div>'
    ),
    (
        '                <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                  <Kpi icon="⚡" label="Active Sessions" value="2" color={C.green} sub="2 bays charging"/>\n                  <Kpi icon="🔌" label="Total Power" value="148 kW" color={C.accent} sub="Bay 1+2 combined"/>\n                  <Kpi icon="💰" label="Revenue Today" value="$38.40" color={C.amber} delta="+18%"/>\n                  <Kpi icon="⚠️" label="Faults Active" value="1" color={C.red} sub="Bay 4 — cable"/>\n                </div>',
        '                <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                  <Kpi icon="⚡" label="Active Sessions" value="2" color={C.green} sub="2 bays charging" tourMode={tourMode} tour={{ title: "Active Charger Sessions", concept: "The number of vehicles currently drawing power at the depot.", value: "Helps monitor immediate grid impact and bay occupancy.", tip: "Note the status changes as cars plug in or unplug." }}/>\n                  <Kpi icon="🔌" label="Total Power" value="148 kW" color={C.accent} sub="Bay 1+2 combined" tourMode={tourMode} tour={{ title: "Total Charger Draw", concept: "Combined electrical power currently delivered to all active charging bays.", value: "Essential for staying under substation load limits and avoiding peak demand fees.", tip: "Watch this number rise and fall dynamically in response to vehicle charging rates." }}/>\n                  <Kpi icon="💰" label="Revenue Today" value="$38.40" color={C.amber} delta="+18%" tourMode={tourMode} tour={{ title: "Depot Revenue", concept: "Estimated charging fees collected from vehicles today.", value: "Tracks charger profitability and financial performance in real time.", tip: "Point out the delta percentage showing revenue growth compared to yesterday." }}/>\n                  <Kpi icon="⚠️" label="Faults Active" value="1" color={C.red} sub="Bay 4 — cable" tourMode={tourMode} tour={{ title: "System Health Errors", concept: "The count of chargers currently reporting hardware issues or connection failures.", value: "Alerts maintenance teams immediately, reducing charger downtime and driver frustration.", tip: "Show how a red status alert highlights bays requiring immediate physical attention." }}/>\n                </div>'
    ),

    # Finder Tab
    (
        '                <div style={{display:"flex",gap:8,alignItems:"center",padding:"10px 14px",background:C.surface,border:`1px solid ${C.border}`,borderRadius:12}}>\n                  <span style={{fontSize:16}}>📍</span>\n                  <input placeholder="Search location..." style={{border:"none",background:"none",outline:"none",fontSize:13,flex:1,fontFamily:"\'DM Sans\',sans-serif"}}/>\n                </div>',
        '                <div style={{display:"flex",gap:8,alignItems:"center",padding:"10px 14px",background:C.surface,border:`1px solid ${C.border}`,borderRadius:12}}>\n                  <span style={{fontSize:16}}>📍</span>\n                  <input placeholder="Search location..." style={{border:"none",background:"none",outline:"none",fontSize:13,flex:1,fontFamily:"\'DM Sans\',sans-serif"}}/>\n                  {tourMode && <TourHelper tourMode={tourMode} title="Charger Search & Filter" concept="Find charging stations by city, street, connector type (CCS/NACS), and power rating." value="Helps fleet managers and drivers locate compatible, open stations along their route instantly." tip="Explain how filtering for \'NACS\' narrows the list to high-speed connectors matching the vehicle." />}\n                </div>'
    ),
    (
        '                {filteredStations.map((s,i)=>(\n                  <Card key={i} hover onClick={()=>setExpandStation(expandStation===i?null:i)}>',
        '                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", margin: "4px 0" }}>\n                  <span style={{ fontSize: 11, fontWeight: 700, color: C.textMuted }}>NEARBY STATIONS</span>\n                  {tourMode && <TourHelper tourMode={tourMode} title="Station Availability Details" concept="Real-time list of nearby stations showing connector speeds, pricing, ratings, and stall occupancy." value="Minimizes wait times and avoids driving to full or broken chargers." tip="Expand a station card to show community check-ins and the \'Reserve Stall\' option." />}\n                </div>\n                {filteredStations.map((s,i)=>(\n                  <Card key={i} hover onClick={()=>setExpandStation(expandStation===i?null:i)}>'
    ),
    (
        '<button onClick={e=>{e.stopPropagation();setReserveStation(i);setReserveCountdown(480);setActiveAlert({msg:`✅ Stall reserved at ${s.name} — expires in 8 min`,color:C.green});setTimeout(()=>setActiveAlert(null),3500);}} style={{flex:2,padding:"8px",background:C.accent,border:"none",borderRadius:9,color:C.white,fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"\'DM Sans\',sans-serif"}}>Reserve Stall</button>',
        '<span style={{ flex: 2, display: "inline-flex", alignItems: "center", gap: 4 }}><button onClick={e=>{e.stopPropagation();setReserveStation(i);setReserveCountdown(480);setActiveAlert({msg:`✅ Stall reserved at ${s.name} — expires in 8 min`,color:C.green});setTimeout(()=>setActiveAlert(null),3500);}} style={{width: "100%", padding:"8px",background:C.accent,border:"none",borderRadius:9,color:C.white,fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"\'DM Sans\',sans-serif"}}>Reserve Stall</button><TourHelper tourMode={tourMode} title="Remote Stall Reservation" concept="Locks a charging stall for your vehicle for a short window while you drive there." value="Guarantees a stall is waiting for you, preventing other vehicles from taking it." tip="Click \'Reserve Stall\' to start the live 8-minute countdown timer. You will see a green reservation banner." /></span>'
    ),
    (
        '<div style={{position:"absolute",bottom:16,left:"50%",transform:"translateX(-50%)",background:"white",borderRadius:99,padding:"8px 16px",fontSize:12,color:C.textMuted,boxShadow:C.shadow,fontWeight:500}}>🗺 Interactive map — {filteredStations.length} stations shown</div>',
        '<div style={{position:"absolute",bottom:16,left:"50%",transform:"translateX(-50%)",background:"white",borderRadius:99,padding:"8px 16px",fontSize:12,color:C.textMuted,boxShadow:C.shadow,fontWeight:500,display:"flex",alignItems:"center"}}><span>🗺 Interactive map — {filteredStations.length} stations shown</span><TourHelper tourMode={tourMode} title="Geographic Status Map" concept="Visual map plot showing charger locations color-coded by occupancy (green = open, red = full)." value="Provides a spatial overview of charger density and status to aid route selection." tip="Note the relative locations of high-speed charging pins compared to the driver\'s current position." /></div>'
    ),

    # Trip Planner Tab
    (
        '<SL>AI-Powered Route Planner</SL>',
        '<SL tourMode={tourMode} tour={{ title: "AI Route Planner", concept: "Calculates the best travel route and schedules charger stops automatically based on battery level, topography, and weather.", value: "Eliminates \'range anxiety\' by ensuring you never run out of charge during a long-distance road trip.", tip: "Type starting and destination cities, select a route preference (Fastest vs Cheapest), and click \'Plan Route\'." }}>AI-Powered Route Planner</SL>'
    ),
    (
        '<SL right="View All">Saved Trips</SL>',
        '<SL right="View All" tourMode={tourMode} tour={{ title: "Saved Route History", concept: "A library of frequently driven routes and their pre-computed charger stops.", value: "Saves planning time for repeated fleet deliveries or daily employee commutes.", tip: "Click \'Use\' on the Los Angeles route to instantly display its calculated charging schedule." }}>Saved Trips</SL>'
    ),
    (
        '<SL right="New York → Boston">Route Plan</SL>',
        '<SL right="New York → Boston" tourMode={tourMode} tour={{ title: "Optimal Route Segments", concept: "Step-by-step driving directions showing exactly when to stop, how long to charge, and what SoC (State of Charge) to expect.", value: "Guarantees drivers spend minimal time waiting at chargers by routing to the fastest available stalls.", tip: "Point out the Milford, CT stop: the AI schedules a brief 22-minute charge to reach the final destination efficiently." }}>Route Plan</SL>'
    ),
    (
        '                    <div style={{marginTop:14,display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>\n                      {[{icon:"🌤",label:"Weather",val:"72°F Sunny"}',
        '                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 14, marginBottom: 8 }}>\n                      <span style={{ fontSize: 11, fontWeight: 700, color: C.textMuted }}>ENVIRONMENTAL FACTORS</span>\n                      {tourMode && <TourHelper tourMode={tourMode} title="External Environmental Factors" concept="Real-time updates on weather, terrain elevation, wind speeds, and highway traffic conditions." value="Allows the AI to adjust range predictions dynamically, preventing battery exhaustion due to cold weather or uphill driving." tip="Note how the moderate traffic and headwind factors are factored into the estimated travel duration." />}\n                    </div>\n                    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>\n                      {[{icon:"🌤",label:"Weather",val:"72°F Sunny"}'
    ),
    (
        '<SL>Route Charging Cost Breakdown</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Trip Charging Cost Audit", concept: "Compares trip energy costs across standard public rates, off-peak pricing, solar sync, and V2G energy credits.", value: "Demonstrates how using smart-charging networks and solar integration cuts trip expenses by over 60%.", tip: "Observe the cost drops: off-peak and solar rates are less than half the standard rate." }}>Route Charging Cost Breakdown</SL>'
    ),

    # Analytics Tab
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:12}}>\n                <Kpi icon="⚡" label="Sessions" value={statPeriod==="week"?"7":statPeriod==="month"?"28":"134"} color={C.accent} delta="+12%" sub="vs last period"/>\n                <Kpi icon="🔋" label="Energy (kWh)" value={statPeriod==="week"?"277":statPeriod==="month"?"1,104":"2,841"} color={C.green} delta="+8%"/>\n                <Kpi icon="💳" label="Total Cost" value={statPeriod==="week"?"$48":statPeriod==="month"?"$189":"$612"} color={C.amber} delta="-5%"/>\n                <Kpi icon="🌱" label="CO₂ Saved" value={statPeriod==="week"?"107kg":statPeriod==="month"?"426kg":"1.1t"} color={C.teal} delta="+15%"/>\n                <Kpi icon="💰" label="vs Gas Savings" value={statPeriod==="week"?"$68":statPeriod==="month"?"$271":"$987"} color={C.green} delta="+11%"/>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:12}}>\n                <Kpi icon="⚡" label="Sessions" value={statPeriod==="week"?"7":statPeriod==="month"?"28":"134"} color={C.accent} delta="+12%" sub="vs last period" tourMode={tourMode} tour={{ title: "Charging Session Count", concept: "The total number of charging events completed in the selected time period.", value: "Helps analyze charger utilization rates and vehicle usage patterns.", tip: "Toggle between week, month, and year periods to see usage density change." }}/>\n                <Kpi icon="🔋" label="Energy (kWh)" value={statPeriod==="week"?"277":statPeriod==="month"?"1,104":"2,841"} color={C.green} delta="+8%" tourMode={tourMode} tour={{ title: "Total Grid Energy Drawn", concept: "The total electrical energy in kilowatt-hours (kWh) consumed by chargers.", value: "Provides raw electricity consumption metrics needed for carbon reporting and utility budgeting.", tip: "Show how total energy consumption tracks closely with vehicle mileage." }}/>\n                <Kpi icon="💳" label="Total Cost" value={statPeriod==="week"?"$48":statPeriod==="month"?"$189":"$612"} color={C.amber} delta="-5%" tourMode={tourMode} tour={{ title: "Depot Electricity Cost", concept: "Total utility expenses incurred for charging operations in the selected timeframe.", value: "Provides direct financial tracking of charging network operating expenses.", tip: "Compare this cost with fuel costs to see the massive savings of electric fleets." }}/>\n                <Kpi icon="🌱" label="CO₂ Saved" value={statPeriod==="week"?"107kg":statPeriod==="month"?"426kg":"1.1t"} color={C.teal} delta="+15%" tourMode={tourMode} tour={{ title: "Carbon Emissions Avoided", concept: "Calculates kilograms of CO2 saved compared to driving conventional gasoline emissions.", value: "Provides verified environmental metrics for corporate sustainability audits and ESG compliance.", tip: "Show off this metric to clients interested in carbon footprint reductions." }}/>\n                <Kpi icon="💰" label="vs Gas Savings" value={statPeriod==="week"?"$68":statPeriod==="month"?"$271":"$987"} color={C.green} delta="+11%" tourMode={tourMode} tour={{ title: "Fuel Displacement Value", concept: "Net financial savings achieved by choosing electricity over commercial gasoline.", value: "Proves the financial return on investment (ROI) of transition to electric vehicles.", tip: "Point out that charging electricity costs are a fraction of gas fuel prices." }}/>\n              </div>'
    ),
    (
        '                    <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><span style={{fontSize:20}}>🤖</span><span style={{fontSize:14,fontWeight:700}}>AI Smart Charging Savings</span></div>',
        '                    <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><span style={{fontSize:20}}>🤖</span><span style={{fontSize:14,fontWeight:700}}>AI Smart Charging Savings</span><TourHelper tourMode={tourMode} title="AI Savings Ledger" concept="Compares actual electricity billing (managed by AI) against standard flat-rate charging costs." value="Quantifies the exact savings generated by the AI\'s smart scheduler and V2G export features." tip="Note the purple \'44% reduction\' badge, highlighting the system\'s automated cost-cutting power." /></div>'
    ),
    (
        '<SL right="277 kWh total">Energy by Day</SL>',
        '<SL right={`${statPeriod==="week"?"277":statPeriod==="month"?"1,104":"2,841"} kWh total`} tourMode={tourMode} tour={{ title: "Daily Consumption Trend", concept: "Graphs daily electricity usage in kWh for the selected time range.", value: "Helps identify anomalous consumption days and peak usage periods.", tip: "Hover over the highest bars to identify peak fleet dispatch days." }}>Energy by Day</SL>'
    ),
    (
        '<SL>Where You Charge</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Charging Location Distribution", concept: "Breaks down total energy consumption by charger type: Home, Workplace, or Public DC Fast chargers.", value: "Helps fleet managers optimize charger placements and verify if drivers are charging at the cheapest locations.", tip: "Point out that Home charging represents 52% of total use, which is the cheapest charging category." }}>Where You Charge</SL>'
    ),
    (
        '<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><SL>Monthly Cost Trend</SL>',
        '<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><SL tourMode={tourMode} tour={{ title: "Cost Trend Sparkline", concept: "Displays the month-over-month trajectory of electricity costs and average session spending.", value: "Allows financial auditors to forecast energy bills and track budgeting compliance.", tip: "Compare the cheapest session cost ($2.10) with the average ($8.40) to show off off-peak scheduling benefits." }}>Monthly Cost Trend</SL>'
    ),
    (
        '<SL right="View All">Recent Sessions</SL>',
        '<SL right="View All" tourMode={tourMode} tour={{ title: "Historical Session Audit", concept: "Chronological list of completed charging sessions showing date, cost, energy, and energy source.", value: "Maintains absolute traceability for driver expense reimbursement and grid auditing.", tip: "Point out the horizontal color bar: it indicates how much energy came from solar vs battery vs the grid." }}>Recent Sessions</SL>'
    ),

    # Energy Hub Tab
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="☀️" label="Solar Today" value="18.4 kWh" color={C.amber} delta="+23%" sub="7.2 kW current"/>\n                <Kpi icon="🔋" label="Home Battery" value="82%" color={C.green} sub="Powerwall · 9.8 kWh"/>\n                <Kpi icon="🏠" label="Home Usage" value="3.2 kW" color={C.accent} sub="4.1 kWh today"/>\n                <Kpi icon="⚡" label="Grid Import" value="$0.08/kWh" color={C.teal} sub="Off-peak now"/>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="☀️" label="Solar Today" value="18.4 kWh" color={C.amber} delta="+23%" sub="7.2 kW current" tourMode={tourMode} tour={{ title: "Live Rooftop Solar Yield", concept: "Daily accumulated solar energy in kWh, with current solar power generation in kW.", value: "Tracks free, clean energy generation to maximize self-consumption and reduce grid draw.", tip: "Watch this number rise during peak daylight hours." }}/>\n                <Kpi icon="🔋" label="Home Battery" value="82%" color={C.green} sub="Powerwall · 9.8 kWh" tourMode={tourMode} tour={{ title: "Battery Storage Level", concept: "Active charge level of your local backup battery storage unit.", value: "Provides building power security during outages and enables peak load shaving.", tip: "Note the reserve capacity held back to protect against grid failures." }}/>\n                <Kpi icon="🏠" label="Home Usage" value="3.2 kW" color={C.accent} sub="4.1 kWh today" tourMode={tourMode} tour={{ title: "Active Building Draw", concept: "Live electrical power consumed by all household appliances, heating, and lighting.", value: "Monitors real-time demand to prevent overloading local network breakers.", tip: "Turn on heavy equipment to see this value change in real time." }}/>\n                <Kpi icon="⚡" label="Grid Import" value="$0.08/kWh" color={C.teal} sub="Off-peak now" tourMode={tourMode} tour={{ title: "Substation Electricity Pricing", concept: "The current price per kWh charged by the utility grid provider.", value: "Allows you to verify peak-rate hours and check that the system is avoiding expensive grid imports.", tip: "Verify the price matches off-peak rates when grid load is low." }}/>\n              </div>'
    ),
    (
        '<SL right="Today\'s tariff">Electricity Price — 24hr</SL>',
        '<SL right="Today\'s tariff" tourMode={tourMode} tour={{ title: "Utility Price Forecast", concept: "A 24-hour visualization of electricity tariff prices per kWh.", value: "Allows operators to spot peak price hours in advance and configure schedule shifts.", tip: "Highlight the red alert indicating peak pricing between 5:00 PM and 9:00 PM." }}>Electricity Price — 24hr</SL>'
    ),
    (
        '<SL>Rate Schedule</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Utility Rate Tariffs", concept: "Lists specific hourly intervals designated as Peak, Mid-Peak, or Off-Peak by the utility.", value: "Saves money by allowing facilities to configure automated charging rules around these rates.", tip: "Notice the difference: Peak rates are more than triple Off-Peak rates ($0.28 vs $0.08)." }}>Rate Schedule</SL>'
    ),
    (
        '<SL>Live Energy Flow</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Dynamic Energy Flow flowchart", concept: "Tracks real-time energy routing between solar panels, building load, EV chargers, and the grid.", value: "Gives immediate visibility into self-sufficiency rates and active power exports.", tip: "Observe the active flows: green indicates power drawn from local battery storage." }}>Live Energy Flow</SL>'
    ),
    (
        '<SL>Schedule Charging</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Charging Scheduler", concept: "Configure target hours to lock charging, avoiding peak utility rates.", value: "Guarantees EV batteries charge during the cheapest hours, reducing bills by up to 50%.", tip: "Drag the slider to 11:00 PM to schedule charging during off-peak windows." }}>Schedule Charging</SL>'
    ),

    # V2G Export Tab
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="💰" label="V2G Earnings Today" value="$3.40" color={C.purple} delta="+18%" sub="2.1 kWh exported"/>\n                <Kpi icon="📅" label="This Month" value="$42.80" color={C.green} delta="+31%" sub="68.4 kWh exported"/>\n                <Kpi icon="🌐" label="Grid Services" value="Active" color={C.teal} sub="Frequency reg."/>\n                <Kpi icon="🔋" label="Available V2G" value="14 kWh" color={C.accent} sub="Battery reserve: 30%"/>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="💰" label="V2G Earnings Today" value="$3.40" color={C.purple} delta="+18%" sub="2.1 kWh exported" tourMode={tourMode} tour={{ title: "Daily V2G Earnings", concept: "Revenues generated today by discharging EV battery power back to the grid.", value: "Provides immediate financial returns, offsetting vehicle purchasing and electricity costs.", tip: "Note the amount of energy in kWh exported to secure these earnings." }}/>\n                <Kpi icon="📅" label="This Month" value="$42.80" color={C.green} delta="+31%" sub="68.4 kWh exported" tourMode={tourMode} tour={{ title: "Monthly Cumulative Earnings", concept: "Revenues accumulated during the current billing month from grid services.", value: "Allows fleet managers to track monthly ROI and grid service profits.", tip: "Compare this month\'s earnings with historical periods to audit performance." }}/>\n                <Kpi icon="🌐" label="Grid Services" value="Active" color={C.teal} sub="Frequency reg." tourMode={tourMode} tour={{ title: "Active Grid Programs", concept: "The grid services program (e.g., Frequency Regulation) the system is currently participating in.", value: "Qualifies the building for higher incentive rates from the utility provider.", tip: "Status \'Active\' means the system is responding to grid frequency signals." }}/>\n                <Kpi icon="🔋" label="Available V2G" value="14 kWh" color={C.accent} sub="Battery reserve: 30%" tourMode={tourMode} tour={{ title: "Export Capacity Reserve", concept: "The amount of energy in EV batteries currently available to export without violating reserve limits.", value: "Ensures vehicles always retain enough charge for planned trips while exporting excess power.", tip: "Observe the battery reserve limit setting, which controls this capacity." }}/>\n              </div>'
    ),
    (
        '<SL right="Last 12 hours">V2G Export Earnings</SL>',
        '<SL right="Last 12 hours" tourMode={tourMode} tour={{ title: "Hourly Export Revenue", concept: "Graphs V2G revenues earned over the last 12 hours.", value: "Visualizes the precise hours V2G was active and corresponding payouts.", tip: "Notice the peak export between 4:00 AM and 6:00 AM, matching early-morning grid peak demand." }}>V2G Export Earnings</SL>'
    ),
    (
        '<SL>V2G Settings</SL>',
        '<SL tourMode={tourMode} tour={{ title: "V2G Safety Reserve", concept: "Configures the minimum charge level the battery must retain during grid discharging.", value: "Protects vehicle range: the system will never drain your car\'s battery below this limit, guaranteeing you can drive when needed.", tip: "Drag the slider to adjust the minimum reserve (e.g., to 40%). Note the available V2G capacity shifts immediately." }}>V2G Settings</SL>'
    ),
    (
        '<SL right="Last 30 days">V2G Revenue Breakdown</SL>',
        '<SL right="Last 30 days" tourMode={tourMode} tour={{ title: "V2G Revenue Streams", concept: "Breaks down total earnings by grid program: Peak Shaving, Frequency Regulation, Demand Response, and Spot Market sales.", value: "Helps identify which programs generate the most value for your specific fleet setup.", tip: "Point out that Peak Shaving accounts for 43% of earnings, which is your most profitable program." }}>V2G Revenue Breakdown</SL>'
    ),

    # AI Optimizer Logs Tab
    (
        '<div style={{fontSize:16,fontWeight:700}}>AI Decision Log</div>',
        '<div style={{fontSize:16,fontWeight:700,display:"flex",alignItems:"center"}}><span>AI Decision Log</span><TourHelper tourMode={tourMode} title="Transparent AI Operation Log" concept="A detailed list of all automation decisions made by the AI, showing the timestamp, action, type, and reasoning." value="Eliminates the \'black box\' problem of AI, giving operators full auditing capability and peace of mind." tip="Filter by \'savings\' or \'grid\' to view specific actions taken to optimize costs." /></div>'
    ),
    (
        '<SL>AI Optimisation Goal</SL>',
        '<SL tourMode={tourMode} tour={{ title: "AI Prioritisation Goal", concept: "Configures the primary objective the AI optimizes for: Minimising Cost, Maximising Green Energy, or Protecting Battery Life.", value: "Aligns system automated decisions with your current corporate values or financial targets.", tip: "Click \'Minimise Cost\' or \'Protect Battery Life\'. You will see the green active banner update instantly." }}>AI Optimisation Goal</SL>'
    ),
    (
        '<SL>AI Performance This Month</SL>',
        '<SL tourMode={tourMode} tour={{ title: "AI Monthly Performance Audit", concept: "Aggregated stats showing decisions made, grid signals acted on, cost saved, and safety limits enforced.", value: "Allows managers to easily quantify the business value and savings generated by the AI optimizer.", tip: "Show off the \'Faults Detected Early\' metric, highlighting how the AI protects hardware from damage." }}>AI Performance This Month</SL>'
    ),
    (
        '<SL>Static Safety Limits</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Static Safety Enforcements", concept: "Hard-coded safety limits (battery temperature, max voltage, min reserve) that the AI can never override.", value: "Protects physical hardware and vehicle warranties from aggressive AI discharging rules.", tip: "Explain to the client that these safety parameters are locked by engineers and cannot be changed by the AI." }}>Static Safety Limits</SL>'
    ),

    # Fleet Management Tab
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="🚗" label="Total Vehicles" value="4" color={C.accent} sub="3 active · 1 idle"/>\n                <Kpi icon="⚡" label="Currently Charging" value="1" color={C.green} sub="At depot A"/>\n                <Kpi icon="🔋" label="Fleet Avg SoC" value="59%" color={C.amber} sub="Across all vehicles"/>\n                <Kpi icon="💰" label="Fleet Energy Cost" value="$124/mo" color={C.teal} delta="-12%" sub="vs. last month"/>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="🚗" label="Total Vehicles" value="4" color={C.accent} sub="3 active · 1 idle" tourMode={tourMode} tour={{ title: "Fleet Asset Registry", concept: "Total number of electric vehicles registered and tracked in the fleet.", value: "Provides a quick overview of fleet capacity and active deployments.", tip: "Note the active vs idle count to track daily vehicle utilization." }}/>\n                <Kpi icon="⚡" label="Currently Charging" value="1" color={C.green} sub="At depot A" tourMode={tourMode} tour={{ title: "Depot Charging Activity", concept: "The count of fleet vehicles currently connected to depot chargers.", value: "Allows fleet managers to track charging queues and ensure delivery vans are charging on schedule.", tip: "Show that vehicles are charging to meet scheduled departure times." }}/>\n                <Kpi icon="🔋" label="Fleet Avg SoC" value="59%" color={C.amber} sub="Across all vehicles" tourMode={tourMode} tour={{ title: "Average State of Charge", concept: "The mean battery percentage across all vehicles in the fleet.", value: "Gives an immediate gauge of overall fleet energy readiness for new routes.", tip: "If this average is low, check which vehicles require immediate plugging." }}/>\n                <Kpi icon="💰" label="Fleet Energy Cost" value="$124/mo" color={C.teal} delta="-12%" sub="vs. last month" tourMode={tourMode} tour={{ title: "Fleet Charging Expenses", concept: "Accumulated charging utility costs for the entire fleet during the current billing period.", value: "Tracks operating costs to keep fuel expenses within fleet budget limits.", tip: "Point out the green delta percentage showing cost savings compared to last month." }}/>\n              </div>'
    ),
    (
        '<SL right="Manage Fleet">Fleet Vehicles</SL>',
        '<SL right="Manage Fleet" tourMode={tourMode} tour={{ title: "Live Fleet Registry", concept: "Status cards for each vehicle showing battery charge %, active driver, location, and operating status.", value: "Enables real-time fleet dispatching and tracking, ensuring vehicles are charged and ready for their routes.", tip: "Point out the Rivian R1T: it is currently charging at Depot A with a 55% charge level." }}>Fleet Vehicles</SL>'
    ),
    (
        '<SL>Fleet Charging Schedule</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Depot Charging Planner", concept: "Detailed charging schedules and completion targets for each vehicle.", value: "Saves money by automatically scheduling charging for off-peak hours while guaranteeing vehicles are ready by departure.", tip: "Notice the scheduled time for the F-150: charging is deferred to 11:00 PM to save costs." }}>Fleet Charging Schedule</SL>'
    ),
    (
        '<SL>Fleet Health Alerts</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Fleet Diagnostics & Warnings", concept: "Aggregated alerts including low battery warnings, scheduled maintenance triggers, and charger completions.", value: "Prevents operational delays by flagging low-battery vehicles before their shift starts.", tip: "Observe the red alert for the Rivian R1T: it warns the operator of a low 22% charge level needing immediate attention." }}>Fleet Health Alerts</SL>'
    ),

    # User Profile Tab
    (
        '                <Card style={{textAlign:"center",padding:"28px 20px",background:`linear-gradient(145deg,${C.accentLight},${C.surface})`}}>\n                  <div style={{position:"relative",display:"inline-block",marginBottom:14}}>',
        '                <Card style={{textAlign:"center",padding:"28px 20px",background:`linear-gradient(145deg,${C.accentLight},${C.surface})`}}>\n                  <div style={{display:"flex",justifyContent:"flex-end",marginTop:-10,marginRight:-10}}>{tourMode && <TourHelper tourMode={tourMode} title="User Profile Portal" concept="Displays user credentials, loyalty membership tier, and aggregate lifetime savings metrics." value="Personalizes the client workspace and tracks lifetime smart-charging achievements." tip="Highlight the \'Platinum\' status, denoting premium access benefits." />}</div>\n                  <div style={{position:"relative",display:"inline-block",marginBottom:14}}>'
    ),
    (
        '<SL>My Vehicle</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Primary Vehicle Registry", concept: "Details of the active EV registered to this profile, including battery capacity, plug type, and health status.", value: "Allows the software to calibrate optimization algorithms matching the vehicle\'s specific charge curve.", tip: "Observe the registered Tesla Model 3: the system tailors charge voltage and SoC limits to this model." }}>My Vehicle</SL>'
    ),
    (
        '<SL>Payment Methods</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Wallet & Payment Credentials", concept: "Stored payment cards, mobile wallets, or RFID badges linked to the user account.", value: "Enables instant plug-and-charge authorization at public stations without needing physical cards.", tip: "Show how drivers can register local RFID tags to start charger sessions on-site." }}>Payment Methods</SL>'
    ),
    (
        '<SL right={`${badges.filter(b=>b.earned).length}/${badges.length} earned`}>Achievements</SL>',
        '<SL right={`${badges.filter(b=>b.earned).length}/${badges.length} earned`} tourMode={tourMode} tour={{ title: "Green Achievements Ledger", concept: "Unlocks gamified badges (e.g., Solar Master, Grid Friend) for smart energy habits.", value: "Encourages drivers to participate in cost-saving demand response programs.", tip: "Hover over the unlocked Solar Master badge to show how drivers are rewarded for solar-sync charging." }}>Achievements</SL>'
    ),
    (
        '<SL>Settings</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Security & Notification Center", concept: "Access controls to adjust notification preferences, roaming networks, and account privacy.", value: "Ensures compliance with local data privacy laws (GDPR) and gives users full control over alerts.", tip: "Explain to the client how easily notifications can be configured or turned off." }}>Settings</SL>'
    ),

    # Remaining BEMS
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="🌡️" label="Average Indoor Temp" value="21.5°C" color={C.green} sub="Target: 21°C"/>\n                <Kpi icon="❄️" label="HVAC Operating Mode" value={hvacMode.toUpperCase()} color={C.accent} sub={hvacAuto?"AI Auto-optimization active":"Manual override active"} tourMode={tourMode} tour={{ title: "AI HVAC Optimization", concept: "Controls the active state (Cooling, Heating, Ventilation) of the HVAC chillers.", value: "Saves energy by adapting ventilation speeds and coolant flows dynamically based on occupancy.", tip: "Observe how this status changes when BEMS automatically triggers load shedding." }}/>\n                <Kpi icon="💨" label="Fan Status" value={`Speed: ${fanSpeed}`} color={C.teal} sub="Ventilation active"/>\n                <Kpi icon="🔥" label="Boiler Load" value="0%" color={C.red} sub="Status: Standby"/>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="🌡️" label="Average Indoor Temp" value="21.5°C" color={C.green} sub="Target: 21°C" tourMode={tourMode} tour={{ title: "Average Indoor Temp", concept: "The mean temperature of all building zones calculated from indoor thermostat sensors.", value: "Monitors overall thermal comfort while helping audit HVAC cooling efficiency.", tip: "This value fluctuates around the configured target temperature setpoint." }}/>\n                <Kpi icon="❄️" label="HVAC Operating Mode" value={hvacMode.toUpperCase()} color={C.accent} sub={hvacAuto?"AI Auto-optimization active":"Manual override active"} tourMode={tourMode} tour={{ title: "AI HVAC Optimization", concept: "Controls the active state (Cooling, Heating, Ventilation) of the HVAC chillers.", value: "Saves energy by adapting ventilation speeds and coolant flows dynamically based on occupancy.", tip: "Observe how this status changes when BEMS automatically triggers load shedding." }}/>\n                <Kpi icon="💨" label="Fan Status" value={`Speed: ${fanSpeed}`} color={C.teal} sub="Ventilation active" tourMode={tourMode} tour={{ title: "Ventilation Fan Status", concept: "Current speed level of the central air ventilation fans.", value: "Directly impacts building air flow comfort. Lowering fan speed during low occupancy cuts fan electricity consumption.", tip: "Adjust the global fan speed below to watch this value update dynamically." }}/>\n                <Kpi icon="🔥" label="Boiler Load" value="0%" color={C.red} sub="Status: Standby" tourMode={tourMode} tour={{ title: "Central Boiler Load", concept: "Operating percentage of the building\'s central heating boiler.", value: "Shows heating fuel usage. In summer months, this remains at 0% standby to prevent energy waste.", tip: "This status will change to active heating if zone temperature setpoints exceed current ambient room temperatures." }}/>\n              </div>'
    ),
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>\n                <Kpi icon="💡" label="Active Fixtures" value="142 / 180" color={C.green} sub="LED energy saving enabled"/>\n                <Kpi icon="☀️" label="Daylight Harvesting" value={daylightHarvesting?"ACTIVE":"DISABLED"} color={C.accent} sub="Auto dimming active" tourMode={tourMode} tour={{ title: "Daylight Harvesting", concept: "Uses ambient light sensors to dim building lights automatically if sunlight is bright enough.", value: "Saves up to 40% in lighting electricity costs during the day without human intervention.", tip: "Toggle Daylight Harvesting under Automation Settings and watch how it affects lighting levels." }}/>\n                <Kpi icon="⚡" label="Lighting Demand" value="8.4 kW" color={C.teal} sub="Savings vs legacy lighting: -64%"/>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>\n                <Kpi icon="💡" label="Active Fixtures" value="142 / 180" color={C.green} sub="LED energy saving enabled" tourMode={tourMode} tour={{ title: "Active Lighting Fixtures", concept: "The ratio of currently illuminated light fixtures compared to the building total.", value: "Tracks lighting density to audit energy waste in vacant office sections.", tip: "Observe this count decrease when schedule-based sweeps turn off unoccupied office grids." }}/>\n                <Kpi icon="☀️" label="Daylight Harvesting" value={daylightHarvesting?"ACTIVE":"DISABLED"} color={C.accent} sub="Auto dimming active" tourMode={tourMode} tour={{ title: "Daylight Harvesting", concept: "Uses ambient light sensors to dim building lights automatically if sunlight is bright enough.", value: "Saves up to 40% in lighting electricity costs during the day without human intervention.", tip: "Toggle Daylight Harvesting under Automation Settings and watch how it affects lighting levels." }}/>\n                <Kpi icon="⚡" label="Lighting Demand" value="8.4 kW" color={C.teal} sub="Savings vs legacy lighting: -64%" tourMode={tourMode} tour={{ title: "Lighting Electrical Power Draw", concept: "The active power demand in kW consumed by the building\'s LED lights.", value: "Shows live lighting electrical draw. Upgrading to smart LED grids cuts base lighting costs by over 60%.", tip: "Watch this value drop when daylight harvesting dimming is active." }}/>\n              </div>'
    ),
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>\n                <Card>\n                  <SL tourMode={tourMode} tour={{ title: "Live Electricity Meter", concept: "Instantly reports total building electricity consumption (in kW).", value: "Tracks active power draw to catch abnormal usage spikes or device failures in real time.", tip: "Observe how this meter updates every 3 seconds with slight variations, representing a live feed." }}>Electricity Sub-Meter</SL>\n                  <div style={{fontSize:24,fontWeight:800,color:C.accent}}>{electricityMeter.toFixed(1)} kW</div>\n                  <div style={{fontSize:10,color:C.textMuted,marginTop:2}}>Live demand meter · Updated 3s ago</div>\n                </Card>\n                <Card>\n                  <SL>Water Meter</SL>\n                  <div style={{fontSize:24,fontWeight:800,color:C.teal}}>{waterMeter.toFixed(1)} m³/h</div>\n                  <div style={{fontSize:10,color:C.textMuted,marginTop:2}}>Main flow meter · Updated 3s ago</div>\n                </Card>\n                <Card>\n                  <SL>Gas Import Meter</SL>\n                  <div style={{fontSize:24,fontWeight:800,color:C.amber}}>{gasMeter.toFixed(1)} m³/h</div>\n                  <div style={{fontSize:10,color:C.textMuted,marginTop:2}}>Furnace supply line · Updated 3s ago</div>\n                </Card>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>\n                <Card>\n                  <SL tourMode={tourMode} tour={{ title: "Live Electricity Meter", concept: "Instantly reports total building electricity consumption (in kW).", value: "Tracks active power draw to catch abnormal usage spikes or device failures in real time.", tip: "Observe how this meter updates every 3 seconds with slight variations, representing a live feed." }}>Electricity Sub-Meter</SL>\n                  <div style={{fontSize:24,fontWeight:800,color:C.accent}}>{electricityMeter.toFixed(1)} kW</div>\n                  <div style={{fontSize:10,color:C.textMuted,marginTop:2}}>Live demand meter · Updated 3s ago</div>\n                </Card>\n                <Card>\n                  <SL tourMode={tourMode} tour={{ title: "Water Flow Sub-Meter", concept: "Live water flow rate in cubic meters per hour passing through the main supply pipeline.", value: "Tracks facility water utilization and flags continuous flows that might indicate pipe leaks or open valves.", tip: "Observe the slight variations in flow rate, representing active occupant usage." }}>Water Meter</SL>\n                  <div style={{fontSize:24,fontWeight:800,color:C.teal}}>{waterMeter.toFixed(1)} m³/h</div>\n                  <div style={{fontSize:10,color:C.textMuted,marginTop:2}}>Main flow meter · Updated 3s ago</div>\n                </Card>\n                <Card>\n                  <SL tourMode={tourMode} tour={{ title: "Gas Supply Sub-Meter", concept: "Live gas flow rate in cubic meters per hour consumed by heating boilers and furnaces.", value: "Provides raw metrics for heating fuel costs and carbon emission tracking.", tip: "In standby mode, this meter registers 0.0 m³/h, indicating zero fuel burn." }}>Gas Import Meter</SL>\n                  <div style={{fontSize:24,fontWeight:800,color:C.amber}}>{gasMeter.toFixed(1)} m³/h</div>\n                  <div style={{fontSize:10,color:C.textMuted,marginTop:2}}>Furnace supply line · Updated 3s ago</div>\n                </Card>\n              </div>'
    ),
    (
        '<SL>Daily Consumption Summary</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Daily Utility Billing Audit", concept: "Accumulated daily consumption and estimated costs for electricity, water, and gas.", value: "Gives facilities managers daily financial tracking to prevent end-of-month utility bill surprises.", tip: "Compare the daily electricity cost ($409.44) with water ($168.40) to see where major savings can be made." }}>Daily Consumption Summary</SL>'
    ),
    (
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="♻️" label="Optimisation Status" value={sheddingActive?"SHEDDING ACTIVE":"HEALTHY"} color={sheddingActive?C.red:C.green} sub={coOptMode==="auto"?"AI automated dispatching":"Manual profile active"} tourMode={tourMode} tour={{ title: "Optimisation Status", concept: "Tells you if the building is currently shedding load to stay under its limit.", value: "Saves thousands of dollars in peak demand surcharges and prevents electrical failure.", tip: "When shedding is active, AC chillers run at lower speeds and non-essential lights are dimmed." }}/>\n                <Kpi icon="⚡" label="EV Grid Demand" value="98.4 kW" color={C.accent} sub="Total vehicle charging load"/>\n                <Kpi icon="🏢" label="Building Base Demand" value={`${electricityMeter.toFixed(1)} kW`} color={C.purple} sub="HVAC + lighting load"/>\n                <Kpi icon="🛑" label="Building peak Limit" value={`${peakThreshold} kW`} color={C.red} sub="Demand threshold limit" tourMode={tourMode} tour={{ title: "Building Peak Limit", concept: "The maximum power draw allowed for the entire facility.", value: "Capping this limit prevents high charges and guarantees you do not overload your local grid connection.", tip: "This limit is controlled via the slider below." }}/>\n              </div>',
        '              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>\n                <Kpi icon="♻️" label="Optimisation Status" value={sheddingActive?"SHEDDING ACTIVE":"HEALTHY"} color={sheddingActive?C.red:C.green} sub={coOptMode==="auto"?"AI automated dispatching":"Manual profile active"} tourMode={tourMode} tour={{ title: "Optimisation Status", concept: "Tells you if the building is currently shedding load to stay under its limit.", value: "Saves thousands of dollars in peak demand surcharges and prevents electrical failure.", tip: "When shedding is active, AC chillers run at lower speeds and non-essential lights are dimmed." }}/>\n                <Kpi icon="⚡" label="EV Grid Demand" value="98.4 kW" color={C.accent} sub="Total vehicle charging load" tourMode={tourMode} tour={{ title: "EV Charger Demand", concept: "The combined live power load in kW drawn by all vehicles plugged into depot chargers.", value: "Essential for monitoring total facility demand to avoid substation overloads.", tip: "This value increases as vehicles plug in or draw higher charging power levels." }}/>\n                <Kpi icon="🏢" label="Building Base Demand" value={`${electricityMeter.toFixed(1)} kW`} color={C.purple} sub="HVAC + lighting load" tourMode={tourMode} tour={{ title: "Building Base Demand", concept: "Live electricity load consumed by HVAC chillers, lighting, and ventilation systems (excluding EV chargers).", value: "Tracks the building\'s core load footprint to identify baseline energy waste.", tip: "Compare the building base demand with the EV charger demand to see which system is drawing more power." }}/>\n                <Kpi icon="🛑" label="Building peak Limit" value={`${peakThreshold} kW`} color={C.red} sub="Demand threshold limit" tourMode={tourMode} tour={{ title: "Building Peak Limit", concept: "The maximum power draw allowed for the entire facility.", value: "Capping this limit prevents high charges and guarantees you do not overload your local grid connection.", tip: "This limit is controlled via the slider below." }}/>\n              </div>'
    ),
    (
        '<SL>Co-Optimisation Operations Profile</SL>',
        '<SL tourMode={tourMode} tour={{ title: "Optimisation Mode Selector", concept: "Choose between AI co-optimisation (dynamic limit capping), forcing load-shedding manually, or disabling building-to-charger linkage.", value: "Gives facility managers instant override capability to prioritize either grid stability or maximum charger speeds.", tip: "Click \'Force Shedding\' to manually trigger energy conservation rules. Watch the AC chiller load drop to 42%." }}>Co-Optimisation Operations Profile</SL>'
    )
]

applied_count = 0
for target, replacement in replacements:
    if target in content:
        content = content.replace(target, replacement)
        applied_count += 1
    else:
        print(f"Warning: target not found: {repr(target[:60])}")

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Successfully applied {applied_count}/{len(replacements)} replacements.")
