name: Chess Dispatcher

on:
  issues:
    types: [opened]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Chess')
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: DANYALAQEEL/chess-engine-node
          event-type: chess-move
          client-payload: '{"issue_number": "${{ github.event.issue.number }}", "issue_title": "${{ github.event.issue.title }}", "issue_author": "${{ github.event.issue.user.login }}"}'
